import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./authstatus";
import { FooterComp } from "@/components/(Footer)/FooterComp";
import { Chatbox } from "@/components/(chatbox)/chatbox";
import { NavToggle } from "@/app/navstate"
import { Navbar } from "@/components/(navbar)/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "House Mgr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className="text-white overflow-x-hidden">
        <AuthProvider>
          <NavToggle>
            <Navbar />
            {children}
            <FooterComp />
            <Chatbox />
          </NavToggle>
        </AuthProvider>
      </body>
    </html>
  );
}
