import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/(navbar)/navbar";
import { AuthProvider } from "./authstatus";
import { FooterComp } from "@/components/(Footer)/FooterComp";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "House Mgr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className="text-white overflow-x-hidden">
        <AuthProvider>
          <Navbar />
          {children}
          <FooterComp />
        </AuthProvider>
      </body>
    </html>
  );
}
